version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - 3003:3000
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - kbpr_image_folder:/kbpr-web/storage/
    depends_on:
      - postgres
    networks:
      - kbpr-net
  postgres:
    build:
      context: .
      dockerfile: PostgresDockerfile
    restart: always
    volumes:
      - kbpr_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kbpr_web
    env_file:
      - .postgres_password
    networks:
      - kbpr-net
  redis:
    image: redis:7.0-alpine
    restart: always
    volumes:
      - kbpr_redis:/data
    networks:
      - kbpr-net
networks:
  kbpr-net:
volumes:
  kbpr_db:
    external: true
  kbpr_image_folder:
    external: true
  kbpr_redis:
    external: true