version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - 3003:3000
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: PostgresDockerfile
    restart: always
    volumes:
      - kbpr_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kbpr_web
    env_file:
      - .postgres_password
volumes:
  kbpr_db:
    external: true
